### ISSUE TITLE
Issues with getting balance....

### ISSUE THREAD

**Issue by jdorko1337** [blockchain/api-v1-client-python#111]
Ok, so I am having issues getting the address with balance, and the proper balance...
Printing wallet.get_balance() shows the proper ammount in the blockchain wallet.
but when I try to go through the addresses to find which has the balance, then to send it out, The address with balance never comes up, and I get reports of all addresses being at a 0 balance.

Output from Code:
`573
Entire Wallet Balance: 573
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy
Balance: 0 Address: removed for privacy`

Source Code:

`from blockchain.wallet import Wallet
import time
wallet = Wallet('xxxxxxxxxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxx', 'http://localhost:3000/')
print wallet.get_balance()

nobalance = True
while nobalance == True:
	print 'Entire Wallet Balance: ' + str(wallet.get_balance())
	balance = wallet.get_balance()
	addresses = wallet.list_addresses()
	for a in addresses:
		print 'Balance: ' + str(a.balance) + ' Address: ' + a.address
		if a.balance != 0:
			print 'BALANCE Found: ' + str(a.balance) + ':'+ a.address 
			payment = wallet.send('REMOVED FOR PRIVACY', a.balance, a.address)
			print payment.tx_hash
	time.sleep(3)
	print '\n'`

**Comment by jdorko1337** [comment]
Also from `service-my-wallet-v3`
I get this output

> blockchain-wallet-service start --port 3000
1559050845084 - info: blockchain.info wallet service v0.26.3 running on http://127.0.0.1:3000
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (C:\Users\punt\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\bitcoin-sfox-client\lib\sfox.js:56:98)
    at new External (C:\Users\punt\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:27:20)
    at fetchSuccess (C:\Users\punt\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:111:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
