### ISSUE TITLE
Unable to set timeout?

### ISSUE THREAD

**Issue by derrend** [blockchain/api-v1-client-python#19]
With my network connection disabled:

    >>> import time
    >>> from blockchain.exchangerates import get_ticker
    >>> from blockchain import util
    >>> util.TIMEOUT = 5 #time out after 5 seconds
    >>> start = time.time()
    >>> get_ticker()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/blockchain/exchangerates.py", line 16, in get_ticker
        response = util.call_api('ticker' if api_code is None else 'ticker?api_code=' + api_code)
      File "/usr/local/lib/python2.7/dist-packages/blockchain/util.py", line 23, in call_api
        response = urlopen(BASE_URL + resource, payload, timeout = TIMEOUT).read()
      File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 404, in open
        response = self._open(req, data)
      File "/usr/lib/python2.7/urllib2.py", line 422, in _open
        '_open', req)
      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
        return self.do_open(httplib.HTTPSConnection, req)
      File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
    >>> end = time.time()
    >>> print end - start
    40.0375268459
Can anyone tell me what I am doing wrong?
Thanks in advance :)

**Comment by alecalve** [comment]
If you disabled your network connection, you cannot resolve the IP for blockchain.info, therefore you get the error ```[Errno -2] Name or service not known```. If you want if changes to the timeout are taken in account, you should change it to a very small value (0.001 for example).
