### ISSUE TITLE
some module not found

### ISSUE THREAD

**Issue by cmaliwal** [blockchain/api-v1-client-python#73]
```
(envs) rails@rails:~/f$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from blockchain.wallet import Wallet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rails/f/envs/local/lib/python2.7/site-packages/blockchain/__init__.py", line 1, in <module>
    from . import (
  File "/home/rails/f/envs/local/lib/python2.7/site-packages/blockchain/blockexplorer.py", line 8, in <module>
    from enum import Enum
ImportError: No module named enum
>>> from blockchain import blockexplorer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rails/f/envs/local/lib/python2.7/site-packages/blockchain/__init__.py", line 1, in <module>
    from . import (
  File "/home/rails/f/envs/local/lib/python2.7/site-packages/blockchain/blockexplorer.py", line 6, in <module>
    from . import util
ImportError: cannot import name util
>>> from blockchain import util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rails/f/envs/local/lib/python2.7/site-packages/blockchain/__init__.py", line 1, in <module>
    from . import (
  File "/home/rails/f/envs/local/lib/python2.7/site-packages/blockchain/blockexplorer.py", line 6, in <module>
    from . import util
ImportError: cannot import name util
```

**Comment by mlda065** [comment]
I get the same issue.

# Steps to reproduce

Bash script in Linux:

    python3 -m virtualenv env
    pip install requests blockchain
    python -c 'import blockchain'

# Expected result:

No output. Importing the library doesn't raise an error

# Observed result

```
$ python -c 'import blockchain'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/matthew/Documents/Projects/bitcoin_volume/env/local/lib/python2.7/site-packages/blockchain/__init__.py", line 1, in <module>
    from . import (
  File "/home/matthew/Documents/Projects/bitcoin_volume/env/local/lib/python2.7/site-packages/blockchain/blockexplorer.py", line 8, in <module>
    from enum import Enum
ImportError: No module named enum
```

**Comment by mlda065** [comment]
Woops, I just realised that my issue is different. I'm getting an error about the enum library, not the util submodule.

For *my* issue, running `pip install enum` fixed it. So it's a matter of listing enum as a dependency.

**Comment by RayXY** [comment]
Sorry I cannot reproduce the issue above, can you please list the reproduce process?
