### ISSUE TITLE
Error 500 when use Wallet.send()

### ISSUE THREAD

**Issue by andreabellacicca** [blockchain/api-v1-client-python#83]
I'm currently creating a script with python that create a new address, check if balance is greater than zero and if so move the money to another account. 

Everthing works fine till i call the function Wallet.send() that throws an  unknown error

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/blockchain/util.py", line 26, in call_api
    response = urlopen(base_url + resource, payload, timeout=TIMEOUT).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getWalletInfo.py", line 22, in <module>
    mywalletback.send_many({address: 48000})
  File "/usr/local/lib/python3.5/dist-packages/blockchain/wallet.py", line 75, in send_many
    base_url=self.service_url)
  File "/usr/local/lib/python3.5/dist-packages/blockchain/util.py", line 30, in call_api
    raise APIException(handle_response(e.read()), e.code)
blockchain.exceptions.APIException: {"error":"Unexpected error, please try again"}
`

Apparently if I call the url
`http://localhost:3000/merchant/$guid/payment?password=$main_password&second_password=$second_password&to=$address&amount=$amount&from=$from&fee=$fee`

with all the correct field, the server return a 500 error. Just payment. I have not issues at all when I want to create a new address

**Comment by RomanMelnyk113** [comment]
I have exactly the same issue... any updates on this???
