### ISSUE TITLE
Requirements problem on python 3.6

### ISSUE THREAD

**Issue by evgG** [blockchain/api-v1-client-python#85]
Can't install package on python3.6, got next:
`Complete output from command python setup.py egg_info:                                                                                                       
    Traceback (most recent call last):                                                                                                                               
      File "<string>", line 1, in <module>                                                                                                                           
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>                                                                                                   
        import distutils.core                                                                                                                                                                     
      File "/usr/local/lib/python3.6/distutils/core.py", line 16, in <module>                                                                                                                     
        from distutils.dist import Distribution                                                                                                                        
      File "/usr/local/lib/python3.6/distutils/dist.py", line 9, in <module>                                                                                         
        import re                                                                                                                                                         
      File "/usr/local/lib/python3.6/re.py", line 142, in <module>                                                                                                         
        class RegexFlag(enum.IntFlag):                                                                                                                           
    AttributeError: module 'enum' has no attribute 'IntFlag'    `

**Enum** is part of python since 3.4. Fix for 3.6 - #86

**Comment by RayXY** [comment]
Issue fixed with 1.4.3 release
