### ISSUE TITLE
How to access transactions of an address on the second page?

### ISSUE THREAD

**Issue by 540gyro** [blockchain/api-v1-client-python#90]
I collect transactions of a single address and while the variable of n_tx = 262 when I count the downloaded transactions are 50 and I assumed that these are just the transactions from the first page displayed on blockchain.info.

How do I access the other transactions?

Thanks!

**Comment by host2gate** [comment]
i am also looking for the same answer, can anyone please help us?

**Comment by JuviHerman** [comment]
I believe this limit is a result of the default attributes in this API, unless you have an API key.
I actually just received an API key - and still only received 50 transactions tops per address.
If you found a solution, please notify..:)

**Comment by MLPrognosis** [comment]
I still haven't found a solution either, even though I got an API key. How do I use it for example in the following function:

https://blockchain.info/rawaddr/$bitcoin_address

**Comment by 540gyro** [comment]
I got an API code as well but idk if it helps...Regarding the number of txs you can parse...You can get more transactions by manipulating the &offset parameter. If you set offset to 0 (or not at all) then you get the first 50 txs. Setting the offset to 50, you ll skip the first 50, which you already got from the 1st loop and get from 51 to 100... if you set the offset to 100, then you skip the first 100 and so on... so you need to put it a for loop and use floor division (//) and modulus (%) operators to get all the txs.

However in my case, I still get the following error:

urllib.error.HTTPError: HTTP Error 500: Internal Server Error

Full error:

Traceback (most recent call last):
  File "/home/aman/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/aman/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 410, in main
    run()
  File "/home/aman/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 291, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aman/MEGA/University/PhD/Study/Research/Experiment/code_april_2019/core.py", line 5, in <module>
    get_block_details()
  File "/home/aman/MEGA/University/PhD/Study/Research/Experiment/code_april_2019/functions0.py", line 156, in get_block_details
    usock = urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

Any advice on how to get over this is appreciated!

**Comment by 540gyro** [comment]
> I believe this limit is a result of the default attributes in this API, unless you have an API key.
> I actually just received an API key - and still only received 50 transactions tops per address.
> If you found a solution, please notify..:)

The way to get all the transactions is by manipulating the offset parameter. When the offset parameter is 0 then you ll get 50 transactions. So start by running the api s function you re using with &offset = 0, request the transaction info and then increment by 50 to get the next 50 and so on.

Use the // to figure out how to write the for loop and get all the transactions appropriately. Example: An address has 797 transactions
                number_txs = data['n_tx'] #This will return 797
                n = number_txs // 50 # The limit per request is 50 txs
		if n != 0:
			for i in range(n):
				print("offset: ", offset)
				url = "https://blockchain.info/rawaddr/" + "some wallet address" + "?format=json" +"&offset="+str(offset)
				response = requests.get(url)
				data = response.json()
				offset += 50
			url = "https://blockchain.info/rawaddr/" + str(s) + "?format=json" + "&offset=" + str(offset)

The status code 500 is when the server is busy so it basically tells us to stop requesting data. In my case I request data from 6000 blocks. So I wrote a countdown script which runs every time this error shows up.

I hope this helped :)
